<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Campaign;
use App\Models\Category;
use Illuminate\Support\Str;

class CampaignSeeder extends Seeder
{
    public function run(): void
    {
        // Ambil kategori dari database
        $categories = Category::all()->keyBy('name');
        
        $campaigns = [
            [
                'title' => 'Bantuan Pendidikan Anak Yatim',
                'slug' => 'bantuan-pendidikan-anak-yatim',
                'description' => 'Program bantuan pendidikan untuk anak-anak yatim yang membutuhkan dukungan untuk melanjutkan sekolah. Dana yang terkumpul akan digunakan untuk biaya sekolah, buku pelajaran, seragam, dan kebutuhan pendidikan lainnya.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Yatim Dhuafa']->id ?? null,
                'category' => 'yatim-dhuafa',
                'section' => 'featured',
                'target_amount' => 50000000,
                'current_amount' => 25000000,
                'start_date' => now()->subDays(30),
                'end_date' => now()->addDays(60),
                'status' => 'active',
                'is_verified' => true,
            ],
            [
                'title' => 'Operasi Jantung untuk Ahmad',
                'slug' => 'operasi-jantung-untuk-ahmad',
                'description' => 'Ahmad (8 tahun) membutuhkan operasi jantung segera. Keluarga tidak mampu membiayai operasi yang membutuhkan dana sebesar Rp 150 juta. Mari bantu Ahmad mendapatkan kesempatan hidup yang lebih baik.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Kesehatan']->id ?? null,
                'category' => 'medical',
                'section' => 'urgent',
                'target_amount' => 150000000,
                'current_amount' => 75000000,
                'start_date' => now()->subDays(15),
                'end_date' => now()->addDays(45),
                'status' => 'active',
                'is_verified' => true,
            ],
            [
                'title' => 'Pembangunan Masjid Al-Ikhlas',
                'slug' => 'pembangunan-masjid-al-ikhlas',
                'description' => 'Pembangunan masjid untuk masyarakat Desa Sukamaju yang belum memiliki tempat ibadah. Masjid ini akan menjadi pusat kegiatan keagamaan dan sosial masyarakat.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Masjid']->id ?? null,
                'category' => 'mosque',
                'section' => 'popular',
                'target_amount' => 200000000,
                'current_amount' => 120000000,
                'start_date' => now()->subDays(60),
                'end_date' => now()->addDays(90),
                'status' => 'active',
                'is_verified' => true,
            ],
            [
                'title' => 'Beasiswa untuk Mahasiswa Berprestasi',
                'slug' => 'beasiswa-untuk-mahasiswa-berprestasi',
                'description' => 'Program beasiswa untuk mahasiswa berprestasi dari keluarga kurang mampu. Beasiswa ini akan membantu mereka menyelesaikan pendidikan tinggi.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Pendidikan']->id ?? null,
                'category' => 'education',
                'section' => 'new',
                'target_amount' => 75000000,
                'current_amount' => 30000000,
                'start_date' => now()->subDays(10),
                'end_date' => now()->addDays(80),
                'status' => 'active',
                'is_verified' => true,
            ],
            [
                'title' => 'Bantuan Korban Bencana Alam',
                'slug' => 'bantuan-korban-bencana-alam',
                'description' => 'Bantuan darurat untuk korban bencana alam di wilayah Jawa Barat. Dana akan digunakan untuk bantuan makanan, obat-obatan, dan kebutuhan darurat lainnya.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Bencana Alam']->id ?? null,
                'category' => 'disaster',
                'section' => 'urgent',
                'target_amount' => 100000000,
                'current_amount' => 45000000,
                'start_date' => now()->subDays(5),
                'end_date' => now()->addDays(30),
                'status' => 'active',
                'is_verified' => true,
            ],
            [
                'title' => 'Renovasi Panti Asuhan Kasih',
                'slug' => 'renovasi-panti-asuhan-kasih',
                'description' => 'Renovasi gedung panti asuhan yang sudah rusak dan tidak layak huni. Panti ini menampung 50 anak yatim yang membutuhkan tempat tinggal yang aman dan nyaman.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Yatim Dhuafa']->id ?? null,
                'category' => 'orphanage',
                'section' => 'ending_soon',
                'target_amount' => 80000000,
                'current_amount' => 65000000,
                'start_date' => now()->subDays(45),
                'end_date' => now()->addDays(10),
                'status' => 'active',
                'is_verified' => true,
            ],
            [
                'title' => 'Pembangunan Ruang ICU',
                'slug' => 'pembangunan-ruang-icu',
                'description' => 'Pembangunan ruang ICU untuk Rumah Sakit Umum Daerah yang melayani ribuan pasien setiap bulannya. Ruang ICU ini sangat dibutuhkan untuk pasien kritis.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Kesehatan']->id ?? null,
                'category' => 'hospital',
                'section' => 'featured',
                'target_amount' => 300000000,
                'current_amount' => 180000000,
                'start_date' => now()->subDays(20),
                'end_date' => now()->addDays(100),
                'status' => 'active',
                'is_verified' => true,
            ],
            [
                'title' => 'Pembangunan Sekolah Dasar',
                'slug' => 'pembangunan-sekolah-dasar',
                'description' => 'Pembangunan sekolah dasar di desa terpencil yang belum memiliki fasilitas pendidikan. Sekolah ini akan memberikan akses pendidikan untuk 200 anak.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Pendidikan']->id ?? null,
                'category' => 'school',
                'section' => 'new',
                'target_amount' => 120000000,
                'current_amount' => 20000000,
                'start_date' => now()->subDays(3),
                'end_date' => now()->addDays(120),
                'status' => 'active',
                'is_verified' => false,
            ],
            [
                'title' => 'Program Pemberdayaan Masyarakat',
                'slug' => 'program-pemberdayaan-masyarakat',
                'description' => 'Program pemberdayaan masyarakat melalui pelatihan keterampilan dan modal usaha. Program ini akan membantu 100 keluarga untuk mandiri secara ekonomi.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Bantuan Sosial']->id ?? null,
                'category' => 'community',
                'section' => 'popular',
                'target_amount' => 60000000,
                'current_amount' => 35000000,
                'start_date' => now()->subDays(25),
                'end_date' => now()->addDays(70),
                'status' => 'active',
                'is_verified' => true,
            ],
            [
                'title' => 'Penghijauan Hutan Kota',
                'slug' => 'penghijauan-hutan-kota',
                'description' => 'Program penghijauan hutan kota yang sudah gundul. Program ini akan menanam 10.000 pohon untuk mengurangi polusi udara dan memberikan oksigen yang lebih bersih.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Bantuan Sosial']->id ?? null,
                'category' => 'environment',
                'section' => 'new',
                'target_amount' => 40000000,
                'current_amount' => 15000000,
                'start_date' => now()->subDays(7),
                'end_date' => now()->addDays(90),
                'status' => 'active',
                'is_verified' => false,
            ],
            [
                'title' => 'Tebar Paket Sahur dan Buka Puasa untuk Dhuafa',
                'slug' => 'tebar-paket-sahur-dan-buka-puasa-untuk-dhuafa',
                'description' => 'Program berbagi paket sahur dan buka puasa untuk keluarga dhuafa selama bulan Ramadhan. Program ini akan membantu 500 keluarga untuk mendapatkan makanan yang layak.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Yatim Dhuafa']->id ?? null,
                'category' => 'yatim-dhuafa',
                'section' => 'other',
                'target_amount' => 25000000,
                'current_amount' => 8000000,
                'start_date' => now()->subDays(5),
                'end_date' => now()->addDays(25),
                'status' => 'active',
                'is_verified' => true,
            ],
            [
                'title' => 'Hidangan Berkah Ramadhan',
                'slug' => 'hidangan-berkah-ramadhan',
                'description' => 'Program menyediakan hidangan berbuka puasa untuk masyarakat yang membutuhkan. Program ini akan memberikan makanan berkualitas untuk 1000 orang setiap hari selama Ramadhan.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Bantuan Sosial']->id ?? null,
                'category' => 'community',
                'section' => 'other',
                'target_amount' => 35000000,
                'current_amount' => 12000000,
                'start_date' => now()->subDays(3),
                'end_date' => now()->addDays(30),
                'status' => 'active',
                'is_verified' => true,
            ],
            [
                'title' => 'Sedekah Ramadhan Bantu Renovasi Masjid',
                'slug' => 'sedekah-ramadhan-bantu-renovasi-masjid',
                'description' => 'Program renovasi masjid yang sudah rusak melalui sedekah Ramadhan. Masjid ini akan diperbaiki untuk memberikan tempat ibadah yang nyaman bagi jamaah.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Masjid']->id ?? null,
                'category' => 'mosque',
                'section' => 'other',
                'target_amount' => 45000000,
                'current_amount' => 18000000,
                'start_date' => now()->subDays(10),
                'end_date' => now()->addDays(50),
                'status' => 'active',
                'is_verified' => true,
            ],
            [
                'title' => 'Bantuan Hewan Terlantar',
                'slug' => 'bantuan-hewan-terlantar',
                'description' => 'Program bantuan untuk hewan-hewan terlantar yang membutuhkan perawatan dan makanan. Program ini akan membantu 200 hewan terlantar untuk mendapatkan kehidupan yang lebih baik.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Bantuan Sosial']->id ?? null,
                'category' => 'animal',
                'section' => 'other',
                'target_amount' => 15000000,
                'current_amount' => 5000000,
                'start_date' => now()->subDays(2),
                'end_date' => now()->addDays(40),
                'status' => 'active',
                'is_verified' => true,
            ],
            [
                'title' => 'Program Konservasi Lingkungan',
                'slug' => 'program-konservasi-lingkungan',
                'description' => 'Program konservasi lingkungan untuk melindungi ekosistem yang terancam. Program ini akan membantu melestarikan keanekaragaman hayati dan mengurangi dampak perubahan iklim.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Bantuan Sosial']->id ?? null,
                'category' => 'environment',
                'section' => 'other',
                'target_amount' => 60000000,
                'current_amount' => 22000000,
                'start_date' => now()->subDays(15),
                'end_date' => now()->addDays(75),
                'status' => 'active',
                'is_verified' => true,
            ],
            [
                'title' => 'Zakat Mal',
                'slug' => 'zakat-mal',
                'description' => 'Program pengumpulan zakat mal untuk disalurkan kepada mustahik yang berhak menerima zakat. Zakat mal dikenakan atas harta yang dimiliki seperti emas, perak, uang, dan harta lainnya yang telah mencapai nishab.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Zakat']->id ?? null,
                'category' => 'zakat',
                'section' => 'other',
                'target_amount' => 1000000000,
                'current_amount' => 0,
                'start_date' => now(),
                'end_date' => now()->addYear(),
                'status' => 'active',
                'is_verified' => true,
            ],
            [
                'title' => 'Zakat Penghasilan',
                'slug' => 'zakat-penghasilan',
                'description' => 'Program pengumpulan zakat penghasilan untuk disalurkan kepada mustahik yang berhak menerima zakat. Zakat penghasilan dikenakan atas penghasilan dari pekerjaan, profesi, atau usaha yang telah mencapai nishab.',
                'image_url' => '/images/placeholder.svg',
                'category_id' => $categories['Zakat']->id ?? null,
                'category' => 'zakat',
                'section' => 'other',
                'target_amount' => 1000000000,
                'current_amount' => 0,
                'start_date' => now(),
                'end_date' => now()->addYear(),
                'status' => 'active',
                'is_verified' => true,
            ],
        ];

        foreach ($campaigns as $campaign) {
            Campaign::create($campaign);
        }
    }
} 